# Calculating Utility

In [12]:
import nash
import numpy as np

In [13]:
A = [[1,-1], [-1,1]]
A

[[1, -1], [-1, 1]]

we start off with a matching pennies game, to simulate zero sum choices

In [14]:
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [15]:
sigma_r = np.array([.2, .8])
sigma_c = np.array([.4, .6])

strategies in game theory are vectors of probabilities
what we're simulating is the row player is more often choosing the column choice, while it's the reverse for the row player, he chooses the column choice more often

In [17]:
matching_pennies[sigma_r, sigma_c]

array([ 0.12, -0.12])

row player gets -.12 and the column player gets .12

In [18]:
sigma_r = np.array([.8, .2])
sigma_c = np.array([.4, .6])

swaping the probabilities swaps the payoffs

In [19]:
matching_pennies[sigma_r, sigma_c]

array([-0.12,  0.12])

In [20]:
sigma_r = np.array([1, 0])
sigma_c = np.array([.4, .6])

In [21]:
matching_pennies[sigma_r, sigma_c]

array([-0.2,  0.2])