In [1]:
!pip3 install nashpy

  Using cached numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
    100% |████████████████████████████████| 50.0MB 32kB/s 
  Running setup.py bdist_wheel for nashpy ... - done
  Stored in directory: /home/t0m/.cache/pip/wheels/f8/3b/4f/522b303ccc962b1c572f583f55489517449b97fd927f395ec1
Successfully built nashpy


In [3]:
import nash
nash.__version__

'0.0.13'

# Demonstrating a Battle of the Sexes game
---
two people will randomly show up somewhere with choices. You know their semi preferences, but hey who knows

In [6]:
A = [[3,1], [0,2]]
B = [[2,1], [0,3]]
battle_of_the_sexes = nash.Game(A, B)
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

# Matching Pennies

In [8]:
A = [[1,-1], [-1,1]]
B = [[-1,1], [1,-1]]
matching_pennies = nash.Game(A, B)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [9]:
matching_pennies = nash.Game(A)

In [10]:
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]